### ISSUE TITLE
What to Import from Neon for existing Members

### ISSUE THREAD

**Issue by AricStewart** [CON-In-A-Box/CIAB-Portal#149]
Moving members from Neon to our own database. What do we import?
`
/* updated */

    'Members' => [
        'AccountID' => 'INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT',
        'FirstName' => 'VARCHAR(50)',
        'MiddleName' => 'VARCHAR(50)',
        'LastName' => 'VARCHAR(50)',
        'Suffix' => 'VARCHAR(50)',
        'Login' => 'VARCHAR(50) UNIQUE',
        'Email' => 'VARCHAR(50)',
        'Email2' => 'VARCHAR(50)',
        'Email3' => 'VARCHAR(50)',
        'Phone' => 'VARCHAR(50)',
        'Phone2' => 'VARCHAR(50)',
        'AddressLine1' => 'VARCHAR(200)',
        'AddressLine2' => 'VARCHAR(200)',
        'AddressCity' => 'VARCHAR(200)',
        'AddressState' => 'VARCHAR(50)',
        'AddressZipCode' => 'VARCHAR(20)',
        'AddressZipCodeSuffix' => 'VARCHAR(20)',
        'AddressCountry' => 'VARCHAR(50)',
        'AddressProvince' => 'VARCHAR(50)',
        'Deceased' => 'BIT',
        'DoNotContact' => 'BIT',
        'EmailOptOut' => 'BIT',
        'Birthdate' => 'DATE',
        'Gender' => 'VARCHAR(50)',
        /* from custom fields */
        'PreferredFirstName' => 'VARCHAR(50)',
        'PreferredLastName' => 'VARCHAR(50)',
    ],
`
Are then any other custom fields left that are important?

Anything missing?

**Comment by tskeeley** [comment]
I agree about an authentication table - though I think we need to store a salted key, not the password itself.  (sha256/sha512 salt checking is fairly simple as you know, and will protect us from "leaked data" issues on the host).  On this table, we need to also have "lastChanged" with an autodate on change.  users with system/admin/elevated/concom/etc access likely should change their passwords ever ...  umm, time period, whatever that length is.  (start with year?)  The time period is discussable, but either way, we need the ability to track.

I'm confused at the "OneTIme" field is, unless that's a force-to-change-password flag?  And I presume we would track failed-attempts as well, in case we want to lock accounts automatically from hack attempts?

From the member's table (accounts), I would prefer moving emails to a separate table so we can force unique, even in the three we track.

Drop "AddressType" and "IsPrimaryAddress".  We don't care if they have a summer home, we have one address per user, and that's enough.  I don't want to do a separate address table, because "households" are seriously outmoded in the geek community.  We have WAY to many ties that could be in our out of a single mailing address.  So, we'll let each person have their own.  Since we almost (I can't remember the last time) never use actual mail, addresses are really not important anyway.

You have the only two custom fields that matter to us.  PreferredNames, first and last, are what we need.  Legal name is needed for records.  All of the hotel info is moot.  The concom info is imported as of DB152, the Attendance info is .... hmm, we need to import that too, and I can't remember if we did it in the 152 import.  If not, we need it.

We are going to need other join tables that link accounts in "parent/child", "member/pca", "member/emergency contact", and maybe others.  For now, those are the big ones.  But again, they would be join tables, not part of each record.

We are going to need to add the following fields (pull from neon, likely):
- Deceased
- Do Not Contact
- Email Opt Out

We are likely going to want these as well (though pulling from neon would be possible, it might also be pointless):
- Photo (head and shoulder's shot that we can put on badges if we want)

And do we want these based on the attached ideas:
- Birthdate - We could limit the membership types based on their age as of first day of the event
- Gender - We could capture pronouns (I'm against the extra work of this, but it's possible that people might appreciate it?)  Note: if we do it, we need many genders, not just binary ones - in fact, it might just be easier to store the pronoun and skip the gender all together *shrugs*

**Comment by AricStewart** [comment]
> I agree about an authentication table - though I think we need to store a salted key, not the password itself. (sha256/sha512 salt checking is fairly simple as you know, and will protect us from "leaked data" issues on the host). On this table, we need to also have "lastChanged" with an autodate on change. users with system/admin/elevated/concom/etc access likely should change their passwords ever ... umm, time period, whatever that length is. (start with year?) The time period is discussable, but either way, we need the ability to track.
> 

- I agree. I looked into the various `password_*` functions in PHP and they look pretty good. so using `password_hash` and `password_verify`  think gives us what we want.

- [ ] We want expiring passwords... Ok I can work that in. 

> I'm confused at the "OneTIme" field is, unless that's a force-to-change-password flag? And I presume we would track failed-attempts as well, in case we want to lock accounts automatically from hack attempts?
> 

- It is for when the user click on "forgot my password" we generate a one time password that does not wipe out the old one. 

- [ ] Ok I can add # failed attempts and some sort of lock out. 

> From the member's table (accounts), I would prefer moving emails to a separate table so we can force unique, even in the three we track.

- OK, force unique meaning... Please expand.

> Drop "AddressType" and "IsPrimaryAddress". We don't care if they have a summer home, we have one address per user, and that's enough. I don't want to do a separate address table, because "households" are seriously outmoded in the geek community. We have WAY to many ties that could be in our out of a single mailing address. So, we'll let each person have their own. Since we almost (I can't remember the last time) never use actual mail, addresses are really not important anyway.

- Done

> You have the only two custom fields that matter to us. PreferredNames, first and last, are what we need. Legal name is needed for records. All of the hotel info is moot. The concom info is imported as of DB152, the Attendance info is .... hmm, we need to import that too, and I can't remember if we did it in the 152 import. If not, we need it.

- [ ] Ok get to me if there is more needed but I think for now I will stick with those 2

> We are going to need other join tables that link accounts in "parent/child", "member/pca", "member/emergency contact", and maybe others. For now, those are the big ones. But again, they would be join tables, not part of each record.

- This will require a bit more explanation to me as well. 

> We are going to need to add the following fields (pull from neon, likely):
> 
> Deceased
> Do Not Contact
> Email Opt Out
> We are likely going to want these as well (though pulling from neon would be possible, it might also be pointless):


- [x] Done


> Photo (head and shoulder's shot that we can put on badges if we want)
> And do we want these based on the attached ideas:

- [ ] Humm interesting one. yeah...

> Birthdate - We could limit the membership types based on their age as of first day of the event
> Gender - We could capture pronouns (I'm against the extra work of this, but it's possible that people might appreciate it?) Note: if we do it, we need many genders, not just binary ones - in fact, it might just be easier to store the pronoun and skip the gender all together shrugs

- [x] Added

**Comment by AricStewart** [comment]
Ok I believe in the branch ARIC_import_members has logic that does everything required in this bug. 

I do NOT believe ARIC_import_members should be accepted into the master branch as i believe it is work toward 2019 goals.

If we want to branch the tip to a release branch then we can start putting work like this into the master branch.

**Comment by AricStewart** [comment]
New branch... `ARIC_remove_neon`. That has all the logic for this bug plus more.

**Comment by AricStewart** [comment]
I believe this is all done actually.
