### ISSUE TITLE
Password Reset is not working right

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Portal#281]
@dleverentz Just tried to reset her password to log in to `signin` for pretty much the first time ever. She hit forgot password, got a new password sent to her, and it is not working with either her e-mail address or her username.

**Comment by dleverentz** [comment]
Still having issues with other users. Information available from the reports: 
Jenna Powers-Page <magik.sage@gmail.com> Prompted to change password due to expiration. When she attempted to change her password, a new password reset email was triggered. Her password was never changed. 

Tron Howard <trhoward@gmail.com> Reported that the new password provided in the password request email did not allow him to log in. 

'Damien.ravenwolf@gmail.com'  forwarded the password reset email with no additional information.

**Comment by AricStewart** [comment]
I have fixed a few issues around here and I believe this is functioning now.
