### ISSUE TITLE
Portal, Concom Structure: It should be possible to configure which division backs up which other division.

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Portal#318]
The Divisions have backups defined, in a circular fashion, so that if a director needs to step away or is unavailable, someone is still covering their stuff.

Concom Structure should include the ability to configure who backs up whom.

**Comment by AricStewart** [comment]
Are back-up a strictly designed cycle (as in a division only has 1 backup and all backups complete a cycle including all divisions)

If that strict rule is in effect then it add some complexity to the logic that I am thinking though and wishing I had more graph theory in my background. 

Otherwise it make this issue trivial and complicates issue #319

**Comment by mshappe** [comment]
At any given time Division A backs up Division B, backs up Division C, and so on back around to Division H backing up Division A.

The exact backup cycle varies from year to year.

**Comment by AricStewart** [comment]
Varies year to year, but is always strictly a cycle?
I am brainstorming the best UI and method to allow users to do this in an intuative manor.

**Comment by mshappe** [comment]
Sorry, yes, always strictly a cycle.

--
Michael Scott Shappe
Director, Systems Division
Convergence Events, Inc

Help Amazon donate to CONvergence!
It's free and easy, Amazon does it all!
Always use smile.amazon.com <https://smile.amazon.com/ch/27-1445975>
instead of www!
Learn how <https://smile.amazon.com/ch/27-1445975> 1% of your purchases can
be donated!

**Comment by AricStewart** [comment]
These patches are in.
